app1/urls.py
from django.contrib import admin
from django.urls import path
from app2 import views as ap2v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ap2v.index, name='home'),
    path('registro/', ap2v.reg_user, name='registro'),
    path('login/', ap2v.iniciar_sesion, name='login'),  
    path('logout/', ap2v.cerrar_sesion, name='logout'),
    path('mostrar_proveedores/', ap2v.mostrar_proveedores, name='mostrar_proveedores'),
    path('agregar_proveedor/', ap2v.agregar_proveedor, name='agregar_proveedor'),
    path('mostrar_productos/', ap2v.mostrar_productos, name='mostrar_productos'),
    path('agregar_producto/', ap2v.agregar_producto, name='agregar_producto'),
    path('error_permisos/', ap2v.error_permisos, name='error_permisos'),
    path('agregar_sucursales/', ap2v.agregar_sucursales, name='agregar_sucursales'),
    path('mostrar_sucursales/', ap2v.mostrar_sucursales, name='mostrar_sucursales')
]

app2/models.py
from django.db import models
from django.contrib.auth.models import Group 

class Proveedores(models.Model):
    nombre = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10)

    def __str__(self):
        return self.nombre

class Productos(models.Model):
    nombre = models.CharField(max_length=100)
    stock = models.PositiveIntegerField()
    fk_prov = models.ForeignKey(Proveedores, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Sucursal(models.Model):
    nombre = models.CharField(max_length=80)
    localizacion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre 

Group.objects.get_or_create(name='Cajero')
Group.objects.get_or_create(name='Estudiante')

app2/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from .formularios.registerform import NewUserForm
from .formularios.loginform import LoginForm
from .formularios.ProveedorForm import ProveedorForm
from .formularios.ProductoForm import ProductoForm
from .formularios.SucursalForm import SucursalForm
from django.http import HttpResponseRedirect
from .models import Productos,Proveedores,Sucursal
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages

def reg_user(request):
    if request.method == "POST":
        formulario = NewUserForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect('/')
    else:
        formulario = NewUserForm()
    return render(request, 'Reg_user.html', {'form': formulario})

@login_required(login_url='login')
def index(request):
    es_estudiante = request.user.groups.filter(name='Estudiante').exists()  
    es_admin = request.user.is_staff
    es_cajero = request.user.groups.filter(name='Cajero').exists()
    if es_estudiante or es_admin or es_cajero:
        return render(request,"index.html", {'user': request.user, 'es_estudiante': es_estudiante, 'es_admin': es_admin, 'es_cajero': es_cajero})

def iniciar_sesion(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user =  authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
        else:
            messages.error(request, 'Usuario o contraseña no validos')
            return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    
def cerrar_sesion(request):
    logout(request)
    return redirect('login')


def mostrar_proveedores(request):
    proveedores = Proveedores.objects.all()
    return render(request, 'mostrar_proveedores.html', {'proveedores': proveedores})

@user_passes_test(lambda u: u.is_staff, login_url='error_permisos') 
def agregar_proveedor(request):
    if request.method == "POST":
        form = ProveedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mostrar_proveedores')
    else:
        form = ProveedorForm()
    return render(request, 'agregar_proveedores.html', {'form': form})


def mostrar_productos(request):
    productos = Productos.objects.all()
    return render(request, 'mostrar_productos.html', {'productos': productos})

@user_passes_test(lambda u: u.is_staff, login_url='error_permisos') 
def agregar_producto(request):
    if request.method == "POST":
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mostrar_productos')
    else:
        form = ProductoForm()
    return render(request, 'agregar_producto.html', {'form': form})



def mostrar_sucursales(request):
    sucursal = Sucursal.objects.all()
    return render(request, 'mostrar_sucursal.html', {'Sucursal': sucursal})

@user_passes_test(lambda u: u.is_staff, login_url='error_permisos') 
def agregar_sucursales(request):
    if request.method == "POST":
        form = SucursalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mostrar_sucursales')
    else:
        form = SucursalForm()
    return render(request, 'agregar_sucursal.html', {'form': form})



def error_permisos(request):
    return render(request, 'error_permisos.html')

app2/templates/Reg_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de usuario</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            width: 350px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        .form-group input[type="submit"] {
            background-color: #007BFF;
            color: white;
            cursor: pointer;
            font-size: 16px;
            padding: 12px;
            width: auto;
        }
        .form-group input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{form.username.id_for_label}}">Nombre de usuario:</label>
                {{form.username}}
            </div>

            <div class="form-group">
                <label for="{{form.email.id_for_label}}">Correo electrónico:</label>
                {{form.email}}
            </div>

            <div class="form-group">
                <label for="{{form.password1.id_for_label}}">Contraseña:</label>
                {{form.password1}}
            </div>

            <div class="form-group">
                <label for="{{form.password2.id_for_label}}">Confirmar contraseña:</label>
                {{form.password2}}
            </div>

            <div class="form-group">
                <label for="{{form.group.id_for_label}}">Rol:</label>
                {{form.group}}
            </div>

            <div class="form-group">
                <input type="submit" value="Registrar">
            </div>
        </form>
    </div>
</body>
</html>

app2/templates/agregar_producto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Producto</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-container {
            width: 60%;
            max-width: 400px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }
        .form-group input[type="text"],
        .form-group input[type="number"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        .form-group button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }
        .form-group button:hover {
            background-color: #0056b3;
        }
        .back-button {
            position: absolute;
            top: 10px; /* Ajusta la distancia desde la parte superior */
            left: 10px; /* Ajusta la distancia desde la izquierda */
            padding: 10px 15px; /* Ajusta el tamaño del botón */
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            text-decoration: none; /* Elimina el subrayado del enlace */
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="back-button">Volver</a>
    <div class="form-container">
        <form method="POST" class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                <input type="text" id="id_nombre" name="nombre" required>
            </div>
            <div class="form-group">
                <label for="id_precio">Precio:</label>
                <input type="number" id="id_precio" name="precio" required>
            </div>
            <div class="form-group">
                <label for="id_stock">Stock:</label>
                <input type="number" id="id_stock" name="stock" required>
            </div>
            <div class="form-group">
                <button type="submit">Agregar producto</button>
            </div>
        </form>
    </div>
</body>
</html>

app2/templates/agregar_proveedores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Proveedor</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-container {
            width: 60%;
            max-width: 400px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }
        .form-group input[type="text"],
        .form-group input[type="email"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        .form-group button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }
        .form-group button:hover {
            background-color: #0056b3;
        }
        .back-button {
            position: absolute;
            top: 10px; /* Ajusta la distancia desde la parte superior */
            left: 10px; /* Ajusta la distancia desde la izquierda */
            padding: 10px 15px; /* Ajusta el tamaño del botón */
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            text-decoration: none; /* Elimina el subrayado del enlace */
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="back-button">Volver</a>
    <div class="form-container">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                <input type="text" id="id_nombre" name="nombre" required>
            </div>
            <div class="form-group">
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" name="email" required>
            </div>
            <div class="form-group">
                <label for="id_telefono">Teléfono:</label>
                <input type="text" id="id_telefono" name="telefono" required>
            </div>
            <div class="form-group">
                <button type="submit">Agregar proveedor</button>
            </div>
        </form>
    </div>
</body>
</html>

app2/templates/agregar_sucursal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Sucursal</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-container {
            width: 60%;
            max-width: 400px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }
        .form-group input[type="text"],
        .form-group input[type="number"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        .form-group button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }
        .form-group button:hover {
            background-color: #0056b3;
        }
        .back-button {
            position: absolute;
            top: 10px; /* Ajusta la distancia desde la parte superior */
            left: 10px; /* Ajusta la distancia desde la izquierda */
            padding: 10px 15px; /* Ajusta el tamaño del botón */
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            text-decoration: none; /* Elimina el subrayado del enlace */
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="back-button">Volver</a>
    
    <div class="form-container">
        <form method="POST" class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                <input type="text" id="id_nombre" name="nombre" required>
            </div>
            <div class="form-group">
                <label for="id_localizacion">Localización:</label>
                <input type="text" id="id_localizacion" name="localizacion" required>
            </div>
            <div class="form-group">
                <button type="submit">Agregar Sucursal</button>
            </div>
        </form>
    </div>
</body>
</html>

app2/templates/error_permisos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            text-align: center;
            padding: 50px;
        }
        h1 {
            color: #333;
            font-size: 2.5em;
        }
        p {
            color: #666;
            font-size: 1.2em;
        }
        .error-container {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1);
            padding: 20px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <div class="error-container">
        <h1>Error</h1>
        <p>No tienes permiso para acceder a esta página.</p>
    </div>
</body>
</html>

app2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actividad 19</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        h1 {
            color: #333;
            text-align: center;
            padding: 20px 0;
            font-size: 24px;
            margin-bottom: 30px;
        }
        a {
            margin: 10px auto;
            padding: 10px 20px;
            background-color: #007bff;
            color: #ffffff;
            text-decoration: none;
            text-align: center;
            border: 1px solid #007bff;
            border-radius: 5px;
            width: 200px;
            display: block;
            transition: background-color 0.3s ease;
            font-size: 16px;
        }
        a:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
        .logout-link {
            background-color: #dc3545;
            border-color: #dc3545;
        }
        .logout-link:hover {
            background-color: #c82333;
            border-color: #c82333;
        }
    </style>
</head>
<body>
    {% if es_estudiante or es_admin or es_cajero %}
        <h1> ¡Bienvenido {{ user.username }} al inicio de la página! </h1>
    {% else %}
        <h1> No tienes permisos para acceder a esta página </h1>
    {% endif %}
    <a href="{% url 'agregar_proveedor' %}">Agregar proveedor</a>
    <a href="{% url 'mostrar_proveedores' %}">Mostrar proveedores</a>
    <a href="{% url 'agregar_producto' %}">Agregar producto</a>
    <a href="{% url 'mostrar_productos' %}">Mostrar productos</a>
    <a href="{% url 'agregar_sucursales' %}">Agregar sucursales</a>
    <a href="{% url 'mostrar_sucursales' %}">Mostrar las sucursales</a>
    <a href="{% url 'logout' %}" class="logout-link">Cerrar sesión</a>
</body>
</html>

app2/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar sesión</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5; /* Tonos claros para el fondo */
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            font-size: medium;
        }

        .form-container {
            width: 350px;
            padding: 30px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        .form-group {
            margin-bottom: 20px;
            text-align: left;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #333; /* Color de texto más oscuro */
        }

        .form-group input {
            width: 90%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: medium;
        }

        .form-group input[type="submit"] {
            background-color: #00a7b3;
            color: white;
            cursor: pointer;
            font-size: medium;
            padding: 12px;
            width: auto;
        }

        .form-group input[type="submit"]:hover {
            background-color: #00a7b3;
        }

        .error-message {
            color: red;
            margin-bottom: 15px;
            text-align: center;
        }

        .form-group a {
            text-decoration: none;
            color: #00a7b3;
            font-size: medium;
        }

        .form-group a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <div class="form-container">
        {% if messages %}
        {% for message in messages %}
        <p class="error-message">{{ message }}</p>
        {% endfor %}
        {% endif %}
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">Nombre de usuario:</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="{{ form.password.id_for_label }}">Contraseña:</label>
                {{ form.password }}
            </div>
            <div class="form-group">
                <input type="submit" value="Iniciar sesión">
            </div>
        </form>
        <div class="form-group">
            <a href="{% url 'registro' %}">Registrarse</a>
        </div>
    </div>
</body>

</html>

app2/templates/mostrar_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mostrar Productos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .list-container {
            width: 80%;
            max-width: 800px;
            margin-top: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        h1 {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        .provider-header {
            display: flex;
            justify-content: space-between;
            font-weight: bold;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            margin-bottom: 10px;
        }
        .provider-header div {
            flex: 1;
            text-align: center;
        }
        .list-item {
            display: flex;
            justify-content: space-between;
            padding: 10px 0;
            border-bottom: 1px solid #ddd;
        }
        .list-item:last-child {
            border-bottom: none;
        }
        .provider-info div {
            flex: 1;
            text-align: center;
        }
        .back-button {
            position: absolute;
            top: 10px; /* Ajusta la distancia desde la parte superior */
            left: 10px; /* Ajusta la distancia desde la izquierda */
            padding: 10px 15px; /* Ajusta el tamaño del botón */
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            text-decoration: none; /* Elimina el subrayado del enlace */
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="back-button">Volver</a>
    <div class="list-container">
        <h1>Productos</h1>
        <div class="provider-header">
            <div>Nombre</div>
            <div>Stock</div>
            <div>Proveedor</div>
        </div>
        {% for producto in productos %}
            <div class="list-item">
                <div class="provider-info">
                    <div>{{ producto.nombre }}</div>
                    <div>{{ producto.stock }}</div>
                    <div>{{ producto.fk_prov }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>

app2/templates/mostrar_proveedores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mostrar Proveedores</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .list-container {
            width: 80%;
            max-width: 600px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        h1 {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        .provider-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-weight: bold;
            padding: 10px 0;
            border-bottom: 1px solid #ddd;
        }
        .provider-header div {
            flex: 1;
            text-align: center;
        }
        .list-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
            border-bottom: 1px solid #ddd;
        }
        .list-item:last-child {
            border-bottom: none;
        }
        .provider-info div {
            flex: 1;
            text-align: center;
        }
        .back-button {
            position: absolute;
            top: 10px; /* Ajusta la distancia desde la parte superior */
            left: 10px; /* Ajusta la distancia desde la izquierda */
            padding: 10px 15px; /* Ajusta el tamaño del botón */
            border: none;
            border-radius: 5px;
            background-color: #007BFF;
            color: white;
            text-decoration: none; /* Elimina el subrayado del enlace */
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="back-button">Volver</a>
    <div class="list-container">
        <h1>Proveedores</h1>
        <div class="provider-header">
            <div>Nombre</div>
            <div>Teléfono</div>
        </div>
        {% for proveedor in proveedores %}
            <div class="list-item">
                <div class="provider-info">
                    <div>{{ proveedor.nombre }}</div>
                    <div>{{ proveedor.telefono }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>